name: CI

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
        default: 'chew'

  push:
    branches:
      - '**'

jobs:
  scanner-action-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sonar-less-Scan
        uses: ./
        with:
          sonar-project-version: '0.1'
          sonar-source-path: 'test-src'